# Generated by Django 4.0.5 on 2022-06-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FB_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
